name: Go
on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

    # Setup
    - name: Set up Go 1.13
      uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Checkout repository
      uses: actions/checkout@v2

    # Testing
    - name: Run tests
      run: go test ./...
